spring.application.name=oop

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/oop_rmcs?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=lemmeIn8055
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.frontend.url=http://localhost:5173

app.aws.localstack.endpoint=http://localhost.localstack.cloud:4566
app.aws.region=us-east-1
app.aws.access-key=test
app.aws.secret-key=test
